import { nakopitelniyHolat, type ProgressValuationPage } from '../../lib/construction-document-control';
const HOLAT_BELGI: Record<ReturnType<typeof nakopitelniyHolat>, { matn: string; klass: string }> = {
 normal: { matn: 'normal', klass: 'text-emerald-400' },
 chegara: { matn: 'chegara', klass: 'text-amber-300' },
 ortiqcha: { matn: 'ortiqcha', klass: 'text-rose-400 font-medium' },
 aniq_emas: { matn: 'aniq emas', klass: 'text-amber-300' },
};
const show = (value: number | null) => value == null ? '—' : value;
export function ProgressValuationWorkspace({page}:{page:ProgressValuationPage}){return <section aria-label="Progress valuation F2 workspace" className="overflow-x-auto rounded-xl border border-white/10 p-4"><div className="mb-3 text-sm text-slate-400">{page.totalCount.toLocaleString()} BOQ qator · sahifa {page.query.offset + 1}–{page.query.offset + page.rows.length}</div><table className="w-full min-w-[1680px] text-right text-xs"><thead className="text-slate-400"><tr><th className="text-left">Ish / resurs</th><th>Baseline q.</th><th>Reference narx</th><th>Tasdiqlangan Δ</th><th>Entitlement</th><th>Oldingi</th><th>Joriy</th><th>Nakop.</th><th>Qolgan</th><th>F2 q.</th><th>F2 narx</th><th>F2 summa</th><th>Real xarid</th><th>Farq</th><th>Holat</th><th>Revision</th></tr></thead><tbody>{page.rows.map(row=>{const holat=HOLAT_BELGI[nakopitelniyHolat(row)];return <tr key={row.lineId} className={`border-t border-white/5 ${row.changeKinds.includes('substitution')?'border-l-2 border-l-violet-400/60':row.changeKinds.includes('additional_work')?'border-l-2 border-l-emerald-400/60':''}`}><td className="py-2 text-left">{row.description}<span className="ml-2 text-slate-500">{row.unit}</span>{row.changeKinds.length>0&&<span className="ml-2 text-[10px] text-slate-400">{row.changeKinds.join(', ')}</span>}</td><td>{show(row.baselineQuantity)}</td><td>{show(row.baselineReferencePrice)}</td><td>{row.approvedChangeQuantity}</td><td>{show(row.approvedEntitlementQuantity)}</td><td>{row.previousQuantity}/{show(row.previousValue)}</td><td>{row.currentQuantity}/{show(row.currentValue)}</td><td>{row.cumulativeQuantity}/{show(row.cumulativeValue)}</td><td>{show(row.remainingQuantity)}/{show(row.remainingValue)}</td><td>{row.currentQuantity}</td><td>{show(row.currentF2ValuationPrice)}</td><td>{show(row.currentCertifiedValue)}</td><td>{show(row.actualValue)}</td><td className={row.variance&&row.variance>0?'text-amber-300':''}>{show(row.variance)}</td><td className={holat.klass}>{holat.matn}</td><td className="font-mono">{row.revisionIds.join(', ')}</td></tr>;})}</tbody></table></section>}
