import type { ProgressLine, ProgressLineResult, ProgressValuationInput, ProgressValuationResult } from './types';
const E = 1e-9; export const quantity = (n: number) => Math.round((n + E) * 1e6) / 1e6; export const money = (n: number) => Math.round((n + E) * 100) / 100;
const val = (q: number, p: number) => money(quantity(q) * p);
/** Pure, deterministic valuation; it does not mutate certified history or fetch data. */
export function calculateProgressValuation(input: ProgressValuationInput): ProgressValuationResult {
 if (input.throughPeriod < 0 || input.throughPeriod >= input.periods.length) throw new Error('PROGRESS_PERIOD_OUT_OF_RANGE');
 const active = input.changes.filter(c => c.status === 'approved' && c.effectivePeriodIndex <= input.throughPeriod); const rows: ProgressLineResult[] = input.lines.map(line => {
  const periodQuantity = (index: number) => input.periods[index].lines.filter(x => x.lineId === line.lineId).reduce((sum, x) => sum + x.quantity, 0);
  const previousQuantity = quantity(input.periods.slice(0, input.throughPeriod).reduce((sum, _, i) => sum + periodQuantity(i), 0)); const currentQuantity = quantity(periodQuantity(input.throughPeriod)); const cumulativeQuantity = quantity(previousQuantity + currentQuantity);
  const changes = active.filter(c => c.lineId === line.lineId); const approvedChangeQuantity = quantity(changes.reduce((sum,c) => sum + c.quantityDelta, 0)); const approvedEntitlementQuantity = quantity(line.baselineQuantity + approvedChangeQuantity); const remainingQuantity = quantity(approvedEntitlementQuantity - cumulativeQuantity);
  const previousValue = val(previousQuantity, line.baselineReferencePrice); const currentValue = val(currentQuantity, line.baselineReferencePrice); const cumulativeValue = val(cumulativeQuantity, line.baselineReferencePrice); const remainingValue = val(Math.max(0, remainingQuantity), line.baselineReferencePrice);
  const certified = input.periods.slice(0, input.throughPeriod + 1).flatMap(p => p.lines.filter(x => x.lineId === line.lineId)); const f2Known = certified.length > 0 && certified.every(x => x.f2ValuationPrice !== undefined); const actualKnown = certified.length > 0 && certified.every(x => x.actualProcurementPrice !== undefined); const f2ValuationValue = f2Known ? money(certified.reduce((s,x) => s + val(x.quantity, x.f2ValuationPrice!),0)) : null; const actualValue = actualKnown ? money(certified.reduce((s,x) => s + val(x.quantity, x.actualProcurementPrice!),0)) : null;
  const warnings: ProgressLineResult['warnings'] = []; if (cumulativeQuantity > approvedEntitlementQuantity + E) warnings.push('OVER_CERTIFICATION'); if (certified.some(x => !x.referencePriceSourceId || !x.actualPriceSourceId)) warnings.push('MISSING_PRICE_SOURCE'); if (input.changes.some(c => c.lineId === line.lineId && c.status === 'pending')) warnings.push('PENDING_CHANGE');
  return { lineId:line.lineId,sectionId:line.sectionId,description:line.description,unit:line.unit,baselineQuantity:line.baselineQuantity,baselineReferencePrice:line.baselineReferencePrice,approvedChangeQuantity,approvedEntitlementQuantity,previousQuantity,currentQuantity,cumulativeQuantity,remainingQuantity,previousValue,currentValue,cumulativeValue,remainingValue,f2ValuationValue,actualValue,variance:actualValue === null ? null : money(actualValue-cumulativeValue),revisionIds:[input.estimateRevisionId,...changes.map(c=>c.revisionId),...input.periods.slice(0,input.throughPeriod+1).map(p=>p.revisionId)],warnings};
 });
 const sum = (key: keyof ProgressLineResult) => money(rows.reduce((s,r) => s + (typeof r[key] === 'number' ? r[key] as number : 0),0)); return {input,rows,totals:{previousQuantity:sum('previousQuantity'),currentQuantity:sum('currentQuantity'),cumulativeQuantity:sum('cumulativeQuantity'),remainingQuantity:sum('remainingQuantity'),previousValue:sum('previousValue'),currentValue:sum('currentValue'),cumulativeValue:sum('cumulativeValue'),remainingValue:sum('remainingValue')}};
}
