import type { ParkCloseoutReadModel } from './types';
const period = (id: string, revisionId: string, current = 10) => ({ periodId: id, revisionId, frozen: true, previousQuantity: id === 'f2-01' ? 0 : 10, currentQuantity: current, cumulativeQuantity: id === 'f2-01' ? current : 10 + current, approvedQuantity: 30, previousValue: id === 'f2-01' ? 0 : 1_000, currentValue: current * 100, cumulativeValue: id === 'f2-01' ? current * 100 : 1_000 + current * 100, approvedValue: 3_000, referencePriceSourceId: `estimate-${id}`, actualPriceSourceId: `actual-${id}`, approvedChangeIds: ['change-approved-1'], includedApprovedChangeIds: ['change-approved-1'] });
const baseRequirements = [
  { requirementId: 'contract', type: 'contract' as const, label: 'Shartnoma', required: true, requiresApproved: true },
  { requirementId: 'f2-01', type: 'f2' as const, label: 'F2 01.2026', required: true, periodId: 'f2-01', requiresApproved: true },
  { requirementId: 'nak-01', type: 'nakopitelniy' as const, label: 'Nakopitelniy 01.2026', required: true, periodId: 'f2-01', requiresApproved: true },
  { requirementId: 'aosr', type: 'aosr' as const, label: 'Yashirin ishlar AOSR', required: true, requiresApproved: true },
  { requirementId: 'change-evidence', type: 'change_evidence' as const, label: 'Tasdiqlangan o‘zgarish dalili', required: true, requiresApproved: true },
  { requirementId: 'forma3', type: 'forma3' as const, label: 'Forma-3', required: false, requiresApproved: true, evidenceRule: 'forma3_unresolved' as const },
];
export const completeObjectFixture: ParkCloseoutReadModel = { objectId: 'object-complete', requirements: baseRequirements, exportPeriods: [period('f2-01', 'f2-r1')], documents: [
  { documentId: 'contract-1', objectId: 'object-complete', type: 'contract', status: 'approved' }, { documentId: 'f2-doc-1', objectId: 'object-complete', type: 'f2', periodId: 'f2-01', revisionId: 'f2-r1', status: 'approved' },
  { documentId: 'nak-doc-1', objectId: 'object-complete', type: 'nakopitelniy', periodId: 'f2-01', status: 'approved' }, { documentId: 'aosr-1', objectId: 'object-complete', type: 'aosr', status: 'approved' }, { documentId: 'change-proof-1', objectId: 'object-complete', type: 'change_evidence', status: 'approved', evidenceIds: ['change-approved-1'] },
] };
export const missingF2Fixture: ParkCloseoutReadModel = { ...completeObjectFixture, objectId: 'object-missing-f2', documents: completeObjectFixture.documents.filter(document => document.type !== 'f2').map(document => ({ ...document, objectId: 'object-missing-f2' })) };
export const missingAosrFixture: ParkCloseoutReadModel = { ...completeObjectFixture, objectId: 'object-missing-aosr', documents: completeObjectFixture.documents.filter(document => document.type !== 'aosr').map(document => ({ ...document, objectId: 'object-missing-aosr' })) };
export const supersededDocumentFixture: ParkCloseoutReadModel = { ...completeObjectFixture, objectId: 'object-superseded', documents: completeObjectFixture.documents.filter(document => document.type !== 'contract').concat({ documentId: 'contract-old', objectId: 'object-superseded', type: 'contract', status: 'superseded' }).map(document => ({ ...document, objectId: 'object-superseded' })) };
export const pendingApprovalFixture: ParkCloseoutReadModel = { ...completeObjectFixture, objectId: 'object-pending', documents: completeObjectFixture.documents.map(document => document.type === 'aosr' ? { ...document, objectId: 'object-pending', status: 'pending' as const } : { ...document, objectId: 'object-pending' }) };
export const changeWithoutEvidenceFixture: ParkCloseoutReadModel = { ...completeObjectFixture, objectId: 'object-no-change-evidence', documents: completeObjectFixture.documents.filter(document => document.type !== 'change_evidence').map(document => ({ ...document, objectId: 'object-no-change-evidence' })) };
export const missingCumulativeFixture: ParkCloseoutReadModel = { ...completeObjectFixture, objectId: 'object-no-nak', documents: completeObjectFixture.documents.filter(document => document.type !== 'nakopitelniy').map(document => ({ ...document, objectId: 'object-no-nak' })) };
export const invalidExportFixture: ParkCloseoutReadModel = { ...completeObjectFixture, objectId: 'object-invalid-export', exportPeriods: [{ ...period('f2-01', 'f2-r1', 31), currentValue: 3_100, cumulativeValue: 3_100, actualPriceSourceId: 'estimate-f2-01', includedApprovedChangeIds: [] }] };
