import { ChevronDown, ChevronRight } from 'lucide-react';
import { useState } from 'react';
import { Empty } from './CapabilityTable';
import type { SystemAuditEvent } from './types';
function value(value: unknown) { return value == null ? '—' : typeof value === 'string' ? value : JSON.stringify(value); }
export function AuditTable({ events }: { events: SystemAuditEvent[] }) {
  const [open, setOpen] = useState<string | null>(null);
  if (!events.length) return <Empty label="Audit hodisalari mavjud emas." />;
  return <div className="karta overflow-x-auto"><table className="w-full min-w-[1100px] text-left text-xs"><thead className="bg-surface-2/60 text-text-dim"><tr>{['Vaqt', 'Actor', 'Company / project', 'Amal', 'Entity', 'Operation ID', 'Manba', 'Detail'].map((h) => <th key={h} className="px-4 py-3 font-medium">{h}</th>)}</tr></thead><tbody>{events.map((event) => <><tr className="border-t border-border/70" key={event.id}><td className="px-4 py-3 text-text-dim">{event.timestamp}</td><td className="px-4 py-3">{event.actor || '—'}</td><td className="px-4 py-3 text-text-dim">{event.company || '—'}{event.project && <><br />{event.project}</>}</td><td className="px-4 py-3 text-text">{event.action}</td><td className="px-4 py-3">{event.entity}</td><td className="px-4 py-3 font-mono text-text-dim">{event.operationId || '—'}</td><td className="px-4 py-3 text-text-dim">{event.source || '—'}</td><td className="px-4 py-3"><button aria-expanded={open === event.id} onClick={() => setOpen(open === event.id ? null : event.id)} className="inline-flex items-center gap-1 rounded border border-border px-2 py-1.5 hover:bg-surface-2">{open === event.id ? <ChevronDown size={13} /> : <ChevronRight size={13} />}Ko‘rish</button></td></tr>{open === event.id && <tr key={`${event.id}-detail`} className="border-t border-border/70 bg-surface-2/30"><td colSpan={8} className="p-4"><div className="grid gap-3 md:grid-cols-2"><pre className="overflow-auto rounded bg-bg p-3 text-[11px] text-text-dim">Old: {value(event.oldValue)}</pre><pre className="overflow-auto rounded bg-bg p-3 text-[11px] text-text-dim">Yangi: {value(event.newValue)}</pre></div></td></tr>}</>)}</tbody></table></div>;
}
