import { useMemo, useState } from 'react';
import { AlertTriangle, Eye } from 'lucide-react';
import { Empty } from './CapabilityTable';
import { RetryButton } from './CapabilityControls';
import { SystemStatusBadge } from './SystemStatusBadge';
import type { IncidentSeverity, IncidentStatus, SystemIncident } from './types';
export function IncidentTable({ incidents, onAction }: { incidents: SystemIncident[]; onAction?: (incident: SystemIncident, action: 'details' | 'acknowledge' | 'retry') => void }) {
  const [module, setModule] = useState('all'); const [severity, setSeverity] = useState<'all' | IncidentSeverity>('all'); const [status, setStatus] = useState<'all' | IncidentStatus>('all');
  const rows = useMemo(() => incidents.filter((item) => (module === 'all' || item.module === module) && (severity === 'all' || item.severity === severity) && (status === 'all' || item.status === status)), [incidents, module, severity, status]);
  const modules = Array.from(new Set(incidents.map((item) => item.module)));
  return <div className="space-y-4"><div className="flex flex-wrap gap-2"><select aria-label="Incident module filter" value={module} onChange={(e) => setModule(e.target.value)} className="input px-2 py-1.5 text-xs"><option value="all">Barcha modullar</option>{modules.map((name) => <option value={name} key={name}>{name}</option>)}</select><select aria-label="Incident severity filter" value={severity} onChange={(e) => setSeverity(e.target.value as typeof severity)} className="input px-2 py-1.5 text-xs"><option value="all">Barcha darajalar</option>{(['info', 'warning', 'error', 'critical'] as const).map((item) => <option value={item} key={item}>{item.toUpperCase()}</option>)}</select><select aria-label="Incident status filter" value={status} onChange={(e) => setStatus(e.target.value as typeof status)} className="input px-2 py-1.5 text-xs"><option value="all">Barcha holatlar</option>{(['open', 'acknowledged', 'resolved'] as const).map((item) => <option key={item}>{item}</option>)}</select></div>{rows.length ? <div className="karta overflow-x-auto"><table className="w-full min-w-[960px] text-left text-xs"><thead className="bg-surface-2/60 text-text-dim"><tr>{['Daraja', 'Modul / kod', 'Xabar', 'Soni', 'Birinchi', 'Oxirgi', 'Holat', 'Amal'].map((h) => <th key={h} className="px-4 py-3 font-medium">{h}</th>)}</tr></thead><tbody>{rows.map((item) => <tr key={item.id} className="border-t border-border/70"><td className="px-4 py-3"><SystemStatusBadge status={item.severity} /></td><td className="px-4 py-3"><p>{item.module}</p><p className="mt-1 font-mono text-text-dim">{item.code}</p></td><td className="px-4 py-3 text-text">{item.severity === 'critical' && <AlertTriangle className="mr-1 inline text-danger" size={13} />}{item.message}</td><td className="px-4 py-3">{item.count}</td><td className="px-4 py-3 text-text-dim">{item.firstSeen || '—'}</td><td className="px-4 py-3 text-text-dim">{item.lastSeen || '—'}</td><td className="px-4 py-3 capitalize text-text-dim">{item.status}</td><td className="px-4 py-3"><div className="flex gap-2"><button onClick={() => onAction?.(item, 'details')} className="inline-flex items-center gap-1 rounded border border-border px-2 py-1.5 hover:bg-surface-2"><Eye size={13} />Tafsilot</button>{item.status === 'open' && <button onClick={() => onAction?.(item, 'acknowledge')} className="rounded border border-warn/40 px-2 py-1.5 text-warn hover:bg-warn/10">Qabul qilish</button>}<RetryButton onRetry={() => onAction?.(item, 'retry')} /></div></td></tr>)}</tbody></table></div> : <Empty label="Tanlangan filterlarga mos incident yo‘q." />}</div>;
}
