import { Ban } from 'lucide-react';
import { Empty } from './CapabilityTable';
import { PauseResumeButton, RetryButton } from './CapabilityControls';
import { SystemStatusBadge } from './SystemStatusBadge';
import type { SystemJob } from './types';
export function JobTable({ jobs, onRetry, onPause, onResume, onCancel }: { jobs: SystemJob[]; onRetry?: (job: SystemJob) => void; onPause?: (job: SystemJob) => void; onResume?: (job: SystemJob) => void; onCancel?: (job: SystemJob) => void }) {
  if (!jobs.length) return <Empty label="Hozir faol yoki tarixiy job yo‘q." />;
  return <div className="karta overflow-x-auto"><table className="w-full min-w-[900px] text-left text-xs"><thead className="bg-surface-2/60 text-text-dim"><tr>{['Job', 'Tur / modul', 'Holat', 'Jarayon', 'Boshlangan', 'Davomiylik', 'Actor', 'Retry', 'Boshqaruv'].map((h) => <th key={h} className="px-4 py-3 font-medium">{h}</th>)}</tr></thead><tbody>{jobs.map((job) => <tr className="border-t border-border/70" key={job.id}><td className="px-4 py-3 font-mono text-text">{job.id}</td><td className="px-4 py-3"><p className="text-text">{job.type}</p><p className="mt-1 text-text-dim">{job.module}</p></td><td className="px-4 py-3"><SystemStatusBadge status={job.status} /></td><td className="px-4 py-3 min-w-32">{job.status === 'running' && job.progress != null ? <><div className="h-1.5 overflow-hidden rounded bg-surface-2"><div className="h-full bg-accent" style={{ width: `${Math.max(0, Math.min(100, job.progress))}%` }} /></div><span className="mt-1 block text-text-dim">{job.progress}%</span></> : '—'}</td><td className="px-4 py-3 text-text-dim">{job.startedAt || '—'}</td><td className="px-4 py-3 text-text-dim">{job.duration || '—'}</td><td className="px-4 py-3 text-text-dim">{job.actor || '—'}</td><td className="px-4 py-3 text-text-dim">{job.retryCount ?? 0}</td><td className="px-4 py-3"><div className="flex gap-2">{job.status === 'failed' && <RetryButton onRetry={() => onRetry?.(job)} />}{['running', 'paused'].includes(job.status) && <PauseResumeButton job={job} onPause={() => onPause?.(job)} onResume={() => onResume?.(job)} />}{['queued', 'running', 'paused'].includes(job.status) && <button type="button" onClick={() => onCancel?.(job)} className="inline-flex items-center gap-1 rounded border border-danger/40 px-2 py-1.5 text-danger hover:bg-danger/10"><Ban size={13} />Bekor</button>}</div></td></tr>)}</tbody></table></div>;
}
