const fs=require('fs'),path=require('path'),assert=require('assert');
const src=fs.readFileSync(path.join(__dirname,'..','..','Smeta tizimi','97_T2Storage.js'),'utf8');
const sql=fs.readFileSync(path.join(__dirname,'..','..','supabase','migrations','20260830052000_t2_company_storage_foundation_v1.sql'),'utf8');
const yes=(l,r,t=src)=>{assert(r.test(t),l);console.log('  ✅ '+l);};
const no=(l,r)=>{assert(!r.test(src),l);console.log('  ✅ '+l);};
yes('company workspace bind entrypoint',/function\s+apiT2CompanyStorageBind\s*\(input\)/);
yes('root URL or folder ID extraction',/_t2StorageFolderIdFromInput\(input\.rootFolderId\|\|input\.rootUrl\)/);
yes('Drive metadata verification',/supportsAllDrives:true/);
yes('writable probe',/createFolder\('\.t2-storage-verify-/);
yes('mode detection',/detected='my_drive'/);
yes('mode mismatch guard',/STORAGE_MODE_MISMATCH/);
yes('workspace RPC with version/idempotency',/t2_company_storage_bind_v1[\s\S]*p_operation_id[\s\S]*p_expected_version/);
no('no global root scan',/DriveApp\.searchFiles|ROOT_FOLDER_ID|sozAsosiy\(\)\.rootId/);
const vm=require('vm'); let rpcCalls=0;
const context={DriveApp:{},String,Number,Array,Object,RegExp,_t2Rpc:()=>{rpcCalls++;},_t2Get:()=>[]};
vm.createContext(context); vm.runInContext(src,context);
const denied=context.apiT2CompanyStorageBind({companyId:1,folderId:'abcdefghijk',operationId:'11111111-1111-4111-8111-111111111111'});
assert.strictEqual(denied.ok,false); assert.strictEqual(rpcCalls,0,'missing actor must fail before command');
console.log('  ✅ behavioral missing actor fails before storage command');
yes('SQL workspace command',/create or replace function public\.t2_company_storage_bind_v1/,sql);
yes('SQL stale version guard',/STALE_VERSION/,sql);
yes('SQL legacy flag guard',/t2_company_storage_legacy_flag_ck/,sql);
yes('SQL explicit legacy allowlist',/t2_company_storage_legacy_allowlist[\s\S]*LEGACY_WORKSPACE_FORBIDDEN/,sql);
yes('SQL primary uniqueness',/t2_company_storage_one_primary_active/,sql);
