-- Construction OS hard-domain V3.  Additive: existing contract, request and
-- schedule rows remain the only legacy truths; V3 adds governed lineage.
begin;

do $$ begin
  if to_regclass('public.t2_shartnoma') is null then raise exception 't2_shartnoma required'; end if;
  if to_regclass('public.t2_erp_taminot') is null then raise exception 't2_erp_taminot required'; end if;
  if to_regclass('public.t2_grafik_qator') is null then raise exception 't2_grafik_qator required'; end if;
end $$;

create or replace function public.t2_v3_require_member(p_kompaniya_id bigint, p_actor_id bigint)
returns text language plpgsql security definer set search_path=public,pg_temp as $$
declare v_rol text;
begin
  v_rol := public.t2_actor_kompaniya_azo_tekshir(p_kompaniya_id,p_actor_id);
  if v_rol is null then raise exception 'COMPANY_ACCESS_DENIED' using errcode='42501'; end if;
  return v_rol;
end $$;

create or replace function public.t2_v3_require_write(p_kompaniya_id bigint, p_actor_id bigint)
returns text language plpgsql security definer set search_path=public,pg_temp as $$
declare v_rol text;
begin
  v_rol:=public.t2_v3_require_member(p_kompaniya_id,p_actor_id);
  if v_rol in ('boss','rahbar') then raise exception 'WRITE_PERMISSION_DENIED' using errcode='42501'; end if;
  return v_rol;
end $$;

create or replace function public.t2_v3_require_approve(p_kompaniya_id bigint, p_actor_id bigint)
returns void language plpgsql security definer set search_path=public,pg_temp as $$
declare v_rol text;
begin
  v_rol:=public.t2_v3_require_member(p_kompaniya_id,p_actor_id);
  if v_rol not in ('superadmin','admin','pto') then raise exception 'APPROVAL_PERMISSION_DENIED' using errcode='42501'; end if;
end $$;

-- ── COMMERCIAL V2 ────────────────────────────────────────────────────────
alter table public.t2_shartnoma
  add column if not exists valuta text not null default 'UZS',
  add column if not exists avans_summa numeric null,
  add column if not exists ushlab_qolish_foiz numeric null,
  add column if not exists tolov_muddati_kun integer null,
  add column if not exists kafolat_muddati_kun integer null;
alter table public.t2_shartnoma drop constraint if exists t2_shartnoma_v3_terms;
alter table public.t2_shartnoma add constraint t2_shartnoma_v3_terms check (
  (avans_summa is null or avans_summa >= 0) and
  (ushlab_qolish_foiz is null or ushlab_qolish_foiz between 0 and 100) and
  (tolov_muddati_kun is null or tolov_muddati_kun >= 0) and
  (kafolat_muddati_kun is null or kafolat_muddati_kun >= 0));

create table if not exists public.t2_commercial_operation (
  kompaniya_id bigint not null, operation_id uuid not null, action text not null,
  contract_id bigint not null references public.t2_shartnoma(id) on delete restrict,
  result_version integer not null, created_at timestamptz not null default now(),
  primary key(kompaniya_id,operation_id));
create table if not exists public.t2_change_order (
  id bigint generated by default as identity primary key,
  kompaniya_id bigint not null references public.t2_kompaniya(id) on delete restrict,
  shartnoma_id bigint not null references public.t2_shartnoma(id) on delete restrict,
  loyiha_id bigint null references public.t2_loyiha(id) on delete restrict,
  obyekt_id bigint null references public.t2_obyekt(id) on delete restrict,
  raqam text not null, sabab text not null, summa numeric not null,
  holat text not null default 'draft' check(holat in ('draft','submitted','approved','rejected')),
  operation_id uuid not null, versiya integer not null default 1 check(versiya>0),
  created_by bigint not null references public.t2_foydalanuvchi(id) on delete restrict,
  decided_by bigint null references public.t2_foydalanuvchi(id) on delete restrict,
  decided_at timestamptz null, decision_note text null,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  unique(kompaniya_id,operation_id), unique(shartnoma_id,raqam));
create table if not exists public.t2_change_order_decision_operation (
  kompaniya_id bigint not null, operation_id uuid not null,
  change_order_id bigint not null references public.t2_change_order(id) on delete restrict,
  result_version integer not null, created_at timestamptz not null default now(),
  primary key(kompaniya_id,operation_id));
create index if not exists t2_change_order_contract_idx on public.t2_change_order(kompaniya_id,shartnoma_id,holat,created_at desc);

create or replace function public.t2_commercial_contract_get_v2(p_kompaniya_id bigint,p_actor_id bigint,p_shartnoma_id bigint default null)
returns jsonb language plpgsql stable security definer set search_path=public,pg_temp as $$
begin
  perform public.t2_v3_require_member(p_kompaniya_id,p_actor_id);
  return jsonb_build_object('contracts',coalesce((select jsonb_agg(x order by x->>'raqam') from (
    select jsonb_build_object('contract_id',s.id,'kompaniya_id',s.kompaniya_id,'loyiha_id',s.loyiha_id,
      'raqam',s.raqam,'nom',s.nom,'holat',s.holat,'valuta',s.valuta,
      'contract_value',coalesce(s.jami_nds_bilan,s.summa_bez_nds),'advance_amount',s.avans_summa,
      'retention_percent',s.ushlab_qolish_foiz,'payment_days',s.tolov_muddati_kun,
      'warranty_days',s.kafolat_muddati_kun,'version',s.versiya,
      'approved_change_total',(select coalesce(sum(c.summa),0) from public.t2_change_order c where c.shartnoma_id=s.id and c.holat='approved'),
      'change_orders',coalesce((select jsonb_agg(jsonb_build_object('id',c.id,'raqam',c.raqam,'summa',c.summa,'holat',c.holat,'versiya',c.versiya) order by c.created_at desc) from public.t2_change_order c where c.shartnoma_id=s.id),'[]'::jsonb)) x
    from public.t2_shartnoma s where s.kompaniya_id=p_kompaniya_id and (p_shartnoma_id is null or s.id=p_shartnoma_id)
    limit 200) q),'[]'::jsonb));
end $$;

create or replace function public.t2_commercial_contract_update_v2(p_kompaniya_id bigint,p_actor_id bigint,p_shartnoma_id bigint,p_expected_version integer,p_operation_id uuid,p_terms jsonb)
returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare v public.t2_shartnoma%rowtype; v_op public.t2_commercial_operation%rowtype;
begin
  perform public.t2_v3_require_write(p_kompaniya_id,p_actor_id); if p_operation_id is null then raise exception 'OPERATION_ID_REQUIRED'; end if;
  select * into v_op from public.t2_commercial_operation where kompaniya_id=p_kompaniya_id and operation_id=p_operation_id;
  if found then return jsonb_build_object('ok',true,'contract_id',v_op.contract_id,'version',v_op.result_version,'idempotent',true); end if;
  select * into v from public.t2_shartnoma where id=p_shartnoma_id and kompaniya_id=p_kompaniya_id for update;
  if not found then raise exception 'CONTRACT_NOT_FOUND' using errcode='42501'; end if;
  if p_expected_version is null or v.versiya<>p_expected_version then raise exception 'STALE_VERSION' using errcode='40001'; end if;
  update public.t2_shartnoma set valuta=coalesce(nullif(p_terms->>'valuta',''),valuta),
    avans_summa=coalesce((p_terms->>'advance_amount')::numeric,avans_summa), ushlab_qolish_foiz=coalesce((p_terms->>'retention_percent')::numeric,ushlab_qolish_foiz),
    tolov_muddati_kun=coalesce((p_terms->>'payment_days')::integer,tolov_muddati_kun), kafolat_muddati_kun=coalesce((p_terms->>'warranty_days')::integer,kafolat_muddati_kun),versiya=versiya+1
    where id=v.id returning * into v;
  insert into public.t2_commercial_operation values(p_kompaniya_id,p_operation_id,'update',v.id,v.versiya,now());
  perform public.t2_audit_yoz(p_kompaniya_id,'commercial_contract_update','commercial',null,jsonb_build_object('contract_id',v.id,'version',v.versiya)::text,p_actor_id::text,null);
  return jsonb_build_object('ok',true,'contract_id',v.id,'version',v.versiya,'idempotent',false);
end $$;

create or replace function public.t2_change_order_create_v2(p_kompaniya_id bigint,p_actor_id bigint,p_shartnoma_id bigint,p_operation_id uuid,p_raqam text,p_sabab text,p_summa numeric,p_loyiha_id bigint default null,p_obyekt_id bigint default null)
returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare v_id bigint;
begin
 perform public.t2_v3_require_write(p_kompaniya_id,p_actor_id); if p_operation_id is null then raise exception 'OPERATION_ID_REQUIRED'; end if;
 select id into v_id from public.t2_change_order where kompaniya_id=p_kompaniya_id and operation_id=p_operation_id;
 if found then return jsonb_build_object('ok',true,'change_order_id',v_id,'idempotent',true); end if;
 if not exists(select 1 from public.t2_shartnoma where id=p_shartnoma_id and kompaniya_id=p_kompaniya_id) then raise exception 'CONTRACT_NOT_FOUND' using errcode='42501'; end if;
 if p_loyiha_id is not null and not exists(select 1 from public.t2_loyiha where id=p_loyiha_id and kompaniya_id=p_kompaniya_id) then raise exception 'PROJECT_COMPANY_MISMATCH' using errcode='42501'; end if;
 if p_obyekt_id is not null and not exists(select 1 from public.t2_obyekt where id=p_obyekt_id and kompaniya_id=p_kompaniya_id and (p_loyiha_id is null or loyiha_id=p_loyiha_id)) then raise exception 'OBJECT_PROJECT_MISMATCH' using errcode='42501'; end if;
 if nullif(btrim(p_raqam),'') is null or nullif(btrim(p_sabab),'') is null or p_summa is null then raise exception 'CHANGE_ORDER_FIELDS_REQUIRED'; end if;
 insert into public.t2_change_order(kompaniya_id,shartnoma_id,loyiha_id,obyekt_id,raqam,sabab,summa,operation_id,created_by) values(p_kompaniya_id,p_shartnoma_id,p_loyiha_id,p_obyekt_id,btrim(p_raqam),btrim(p_sabab),p_summa,p_operation_id,p_actor_id) returning id into v_id;
 perform public.t2_audit_yoz(p_kompaniya_id,'change_order_create','commercial',p_obyekt_id,jsonb_build_object('change_order_id',v_id,'contract_id',p_shartnoma_id)::text,p_actor_id::text,null);
 return jsonb_build_object('ok',true,'change_order_id',v_id,'idempotent',false);
end $$;

create or replace function public.t2_change_order_decide_v2(p_kompaniya_id bigint,p_actor_id bigint,p_change_order_id bigint,p_expected_version integer,p_operation_id uuid,p_decision text,p_note text default null)
returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare v public.t2_change_order%rowtype; v_result_version integer;
begin
 perform public.t2_v3_require_approve(p_kompaniya_id,p_actor_id); if p_operation_id is null then raise exception 'OPERATION_ID_REQUIRED'; end if;
 select result_version into v_result_version from public.t2_change_order_decision_operation where kompaniya_id=p_kompaniya_id and operation_id=p_operation_id;
 if found then return jsonb_build_object('ok',true,'change_order_id',p_change_order_id,'version',v_result_version,'idempotent',true); end if;
 select * into v from public.t2_change_order where id=p_change_order_id and kompaniya_id=p_kompaniya_id for update;
 if not found then raise exception 'CHANGE_ORDER_NOT_FOUND' using errcode='42501'; end if;
 if p_expected_version is null or v.versiya<>p_expected_version then raise exception 'STALE_VERSION' using errcode='40001'; end if;
 if v.holat not in ('draft','submitted') or p_decision not in ('approved','rejected') then raise exception 'INVALID_CHANGE_ORDER_TRANSITION'; end if;
 update public.t2_change_order set holat=p_decision,decided_by=p_actor_id,decided_at=now(),decision_note=nullif(btrim(p_note),''),versiya=versiya+1,updated_at=now() where id=v.id returning * into v;
 insert into public.t2_change_order_decision_operation(kompaniya_id,operation_id,change_order_id,result_version) values(p_kompaniya_id,p_operation_id,v.id,v.versiya);
 perform public.t2_audit_yoz(p_kompaniya_id,'change_order_'||p_decision,'commercial',v.obyekt_id,jsonb_build_object('change_order_id',v.id,'version',v.versiya,'operation_id',p_operation_id)::text,p_actor_id::text,null);
 return jsonb_build_object('ok',true,'change_order_id',v.id,'version',v.versiya);
end $$;

-- ── PROCUREMENT / WAREHOUSE V2 ──────────────────────────────────────────
create table if not exists public.t2_material_need_v2 (
 id bigint generated by default as identity primary key, kompaniya_id bigint not null references public.t2_kompaniya(id), loyiha_id bigint null references public.t2_loyiha(id), obyekt_id bigint not null references public.t2_obyekt(id),
 material_id bigint not null, quantity numeric not null check(quantity>0), unit text not null, needed_by date null, operation_id uuid not null, versiya integer not null default 1 check(versiya>0), created_by bigint not null references public.t2_foydalanuvchi(id), created_at timestamptz not null default now(), unique(kompaniya_id,operation_id));
alter table public.t2_erp_taminot add column if not exists material_need_id bigint null references public.t2_material_need_v2(id) on delete restrict;
create index if not exists t2_material_need_v2_scope_idx on public.t2_material_need_v2(kompaniya_id,loyiha_id,obyekt_id,needed_by);

create or replace function public.t2_material_need_create_v2(p_kompaniya_id bigint,p_actor_id bigint,p_obyekt_id bigint,p_loyiha_id bigint,p_material_id bigint,p_quantity numeric,p_unit text,p_needed_by date,p_operation_id uuid)
returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$ declare v_id bigint; begin
 perform public.t2_v3_require_write(p_kompaniya_id,p_actor_id); if p_operation_id is null or p_material_id is null or p_quantity is null or p_quantity<=0 or nullif(btrim(p_unit),'') is null then raise exception 'MATERIAL_NEED_FIELDS_INVALID'; end if;
 select id into v_id from public.t2_material_need_v2 where kompaniya_id=p_kompaniya_id and operation_id=p_operation_id; if found then return jsonb_build_object('ok',true,'material_need_id',v_id,'idempotent',true); end if;
 if not exists(select 1 from public.t2_obyekt where id=p_obyekt_id and kompaniya_id=p_kompaniya_id and (p_loyiha_id is null or loyiha_id=p_loyiha_id)) then raise exception 'OBJECT_PROJECT_MISMATCH' using errcode='42501'; end if;
 insert into public.t2_material_need_v2(kompaniya_id,loyiha_id,obyekt_id,material_id,quantity,unit,needed_by,operation_id,created_by) values(p_kompaniya_id,p_loyiha_id,p_obyekt_id,p_material_id,p_quantity,btrim(p_unit),p_needed_by,p_operation_id,p_actor_id) returning id into v_id;
 return jsonb_build_object('ok',true,'material_need_id',v_id,'idempotent',false); end $$;

create or replace function public.t2_procurement_pr_create_v2(p_kompaniya_id bigint,p_actor_id bigint,p_material_need_id bigint,p_item_text text,p_operation_id uuid)
returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$ declare n public.t2_material_need_v2%rowtype; v_id bigint; begin
 perform public.t2_v3_require_write(p_kompaniya_id,p_actor_id); if p_operation_id is null then raise exception 'OPERATION_ID_REQUIRED'; end if;
 select id into v_id from public.t2_erp_taminot where kompaniya_id=p_kompaniya_id and operation_id=p_operation_id; if found then return jsonb_build_object('ok',true,'request_id',v_id,'idempotent',true); end if;
 select * into n from public.t2_material_need_v2 where id=p_material_need_id and kompaniya_id=p_kompaniya_id for share; if not found then raise exception 'MATERIAL_NEED_NOT_FOUND' using errcode='42501'; end if;
 insert into public.t2_erp_taminot(kompaniya_id,obyekt_id,material_need_id,material_id,item_text,requested_qty,unit,required_date,requested_by,status,delivered_qty,operation_id,version) values(p_kompaniya_id,n.obyekt_id,n.id,n.material_id,coalesce(nullif(btrim(p_item_text),''),'material#'||n.material_id),n.quantity,n.unit,n.needed_by,p_actor_id::text,'draft',0,p_operation_id,1) returning id into v_id;
 return jsonb_build_object('ok',true,'request_id',v_id,'material_need_id',n.id,'idempotent',false); end $$;

create table if not exists public.t2_procurement_rfq_v2 (
 id bigint generated by default as identity primary key, kompaniya_id bigint not null references public.t2_kompaniya(id), request_id bigint not null references public.t2_erp_taminot(id), operation_id uuid not null, holat text not null default 'open' check(holat in('open','closed','cancelled')), versiya integer not null default 1, created_by bigint not null references public.t2_foydalanuvchi(id), created_at timestamptz not null default now(), unique(kompaniya_id,operation_id));
create table if not exists public.t2_procurement_bid_v2 (
 id bigint generated by default as identity primary key, kompaniya_id bigint not null references public.t2_kompaniya(id), rfq_id bigint not null references public.t2_procurement_rfq_v2(id), supplier_company_id bigint null references public.t2_kompaniya(id), amount numeric not null check(amount>=0), operation_id uuid not null, holat text not null default 'submitted' check(holat in('submitted','withdrawn','awarded','rejected')), versiya integer not null default 1, created_by bigint not null references public.t2_foydalanuvchi(id), created_at timestamptz not null default now(), unique(kompaniya_id,operation_id));
create table if not exists public.t2_procurement_award_v2 (
 id bigint generated by default as identity primary key, kompaniya_id bigint not null references public.t2_kompaniya(id), request_id bigint not null references public.t2_erp_taminot(id), bid_id bigint not null unique references public.t2_procurement_bid_v2(id), purchase_contract_id bigint null references public.t2_shartnoma(id), po_reference text null, operation_id uuid not null, versiya integer not null default 1, awarded_by bigint not null references public.t2_foydalanuvchi(id), created_at timestamptz not null default now(), unique(kompaniya_id,operation_id));
create table if not exists public.t2_procurement_receipt_v2 (
 id bigint generated by default as identity primary key, kompaniya_id bigint not null references public.t2_kompaniya(id), request_id bigint not null references public.t2_erp_taminot(id), award_id bigint null references public.t2_procurement_award_v2(id), quantity numeric not null check(quantity>0), operation_id uuid not null, received_by bigint not null references public.t2_foydalanuvchi(id), received_at timestamptz not null default now(), unique(kompaniya_id,operation_id));
create table if not exists public.t2_procurement_warehouse_movement_v2 (
 id bigint generated by default as identity primary key, kompaniya_id bigint not null references public.t2_kompaniya(id), receipt_id bigint not null unique references public.t2_procurement_receipt_v2(id), request_id bigint not null references public.t2_erp_taminot(id), obyekt_id bigint not null references public.t2_obyekt(id), material_id bigint null, quantity numeric not null check(quantity>0), operation_id uuid not null, created_at timestamptz not null default now(), unique(kompaniya_id,operation_id));
create index if not exists t2_procurement_receipt_request_idx on public.t2_procurement_receipt_v2(kompaniya_id,request_id,received_at desc);

create or replace function public.t2_procurement_rfq_create_v2(p_kompaniya_id bigint,p_actor_id bigint,p_request_id bigint,p_operation_id uuid)
returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$ declare v_id bigint; begin
 perform public.t2_v3_require_write(p_kompaniya_id,p_actor_id); if p_operation_id is null then raise exception 'OPERATION_ID_REQUIRED'; end if;
 select id into v_id from public.t2_procurement_rfq_v2 where kompaniya_id=p_kompaniya_id and operation_id=p_operation_id; if found then return jsonb_build_object('ok',true,'rfq_id',v_id,'idempotent',true); end if;
 if not exists(select 1 from public.t2_erp_taminot where id=p_request_id and kompaniya_id=p_kompaniya_id and status in('approved','procurement')) then raise exception 'REQUEST_NOT_READY_FOR_RFQ' using errcode='42501'; end if;
 insert into public.t2_procurement_rfq_v2(kompaniya_id,request_id,operation_id,created_by) values(p_kompaniya_id,p_request_id,p_operation_id,p_actor_id) returning id into v_id;
 return jsonb_build_object('ok',true,'rfq_id',v_id,'idempotent',false); end $$;

create or replace function public.t2_procurement_bid_submit_v2(p_kompaniya_id bigint,p_actor_id bigint,p_rfq_id bigint,p_supplier_company_id bigint,p_amount numeric,p_operation_id uuid)
returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$ declare v_id bigint; begin
 perform public.t2_v3_require_write(p_kompaniya_id,p_actor_id); if p_operation_id is null or p_amount is null or p_amount<0 then raise exception 'BID_FIELDS_INVALID'; end if;
 select id into v_id from public.t2_procurement_bid_v2 where kompaniya_id=p_kompaniya_id and operation_id=p_operation_id; if found then return jsonb_build_object('ok',true,'bid_id',v_id,'idempotent',true); end if;
 if not exists(select 1 from public.t2_procurement_rfq_v2 where id=p_rfq_id and kompaniya_id=p_kompaniya_id and holat='open') then raise exception 'RFQ_NOT_OPEN' using errcode='42501'; end if;
 if p_supplier_company_id is not null and not exists(select 1 from public.t2_kompaniya where id=p_supplier_company_id and faol) then raise exception 'SUPPLIER_NOT_FOUND' using errcode='42501'; end if;
 insert into public.t2_procurement_bid_v2(kompaniya_id,rfq_id,supplier_company_id,amount,operation_id,created_by) values(p_kompaniya_id,p_rfq_id,p_supplier_company_id,p_amount,p_operation_id,p_actor_id) returning id into v_id;
 return jsonb_build_object('ok',true,'bid_id',v_id,'idempotent',false); end $$;

create or replace function public.t2_procurement_award_v2(p_kompaniya_id bigint,p_actor_id bigint,p_bid_id bigint,p_purchase_contract_id bigint,p_po_reference text,p_operation_id uuid)
returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$ declare v_id bigint; v_request bigint; begin
 perform public.t2_v3_require_approve(p_kompaniya_id,p_actor_id); if p_operation_id is null then raise exception 'OPERATION_ID_REQUIRED'; end if;
 select id into v_id from public.t2_procurement_award_v2 where kompaniya_id=p_kompaniya_id and operation_id=p_operation_id; if found then return jsonb_build_object('ok',true,'award_id',v_id,'idempotent',true); end if;
 select r.request_id into v_request from public.t2_procurement_bid_v2 b join public.t2_procurement_rfq_v2 r on r.id=b.rfq_id where b.id=p_bid_id and b.kompaniya_id=p_kompaniya_id and b.holat='submitted' for update;
 if not found then raise exception 'BID_NOT_AWARDABLE' using errcode='42501'; end if;
 if p_purchase_contract_id is not null and not exists(select 1 from public.t2_shartnoma where id=p_purchase_contract_id and kompaniya_id=p_kompaniya_id) then raise exception 'PO_CONTRACT_MISMATCH' using errcode='42501'; end if;
 insert into public.t2_procurement_award_v2(kompaniya_id,request_id,bid_id,purchase_contract_id,po_reference,operation_id,awarded_by) values(p_kompaniya_id,v_request,p_bid_id,p_purchase_contract_id,nullif(btrim(p_po_reference),''),p_operation_id,p_actor_id) returning id into v_id;
 update public.t2_procurement_bid_v2 set holat='awarded',versiya=versiya+1 where id=p_bid_id; update public.t2_procurement_rfq_v2 set holat='closed',versiya=versiya+1 where id=(select rfq_id from public.t2_procurement_bid_v2 where id=p_bid_id);
 return jsonb_build_object('ok',true,'award_id',v_id,'idempotent',false); end $$;

create or replace function public.t2_procurement_receipt_record_v2(p_kompaniya_id bigint,p_actor_id bigint,p_request_id bigint,p_award_id bigint,p_quantity numeric,p_operation_id uuid)
returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$ declare v_req public.t2_erp_taminot%rowtype; v_id bigint; v_total numeric; begin
 perform public.t2_v3_require_write(p_kompaniya_id,p_actor_id); if p_operation_id is null or p_quantity is null or p_quantity<=0 then raise exception 'RECEIPT_FIELDS_INVALID'; end if;
 select id into v_id from public.t2_procurement_receipt_v2 where kompaniya_id=p_kompaniya_id and operation_id=p_operation_id; if found then return jsonb_build_object('ok',true,'receipt_id',v_id,'idempotent',true); end if;
 select * into v_req from public.t2_erp_taminot where id=p_request_id and kompaniya_id=p_kompaniya_id for update; if not found then raise exception 'REQUEST_NOT_FOUND' using errcode='42501'; end if;
 if p_award_id is not null and not exists(select 1 from public.t2_procurement_award_v2 where id=p_award_id and request_id=p_request_id and kompaniya_id=p_kompaniya_id) then raise exception 'AWARD_REQUEST_MISMATCH' using errcode='42501'; end if;
 select coalesce(sum(quantity),0)+p_quantity into v_total from public.t2_procurement_receipt_v2 where request_id=p_request_id and kompaniya_id=p_kompaniya_id;
 if v_total>v_req.requested_qty then raise exception 'OVER_RECEIPT' using errcode='23514'; end if;
 insert into public.t2_procurement_receipt_v2(kompaniya_id,request_id,award_id,quantity,operation_id,received_by) values(p_kompaniya_id,p_request_id,p_award_id,p_quantity,p_operation_id,p_actor_id) returning id into v_id;
 insert into public.t2_procurement_warehouse_movement_v2(kompaniya_id,receipt_id,request_id,obyekt_id,material_id,quantity,operation_id) values(p_kompaniya_id,v_id,p_request_id,v_req.obyekt_id,v_req.material_id,p_quantity,p_operation_id);
 update public.t2_erp_taminot set delivered_qty=v_total,status=case when v_total=v_req.requested_qty then 'delivered' else 'partially_delivered' end,version=version+1 where id=p_request_id;
 perform public.t2_audit_yoz(p_kompaniya_id,'procurement_receipt','procurement',v_req.obyekt_id,jsonb_build_object('receipt_id',v_id,'request_id',p_request_id,'quantity',p_quantity)::text,p_actor_id::text,null);
 return jsonb_build_object('ok',true,'receipt_id',v_id,'delivered_qty',v_total,'idempotent',false); end $$;

create or replace function public.t2_procurement_overview_v2(p_kompaniya_id bigint,p_actor_id bigint,p_loyiha_id bigint default null)
returns jsonb language plpgsql stable security definer set search_path=public,pg_temp as $$ begin
 perform public.t2_v3_require_member(p_kompaniya_id,p_actor_id);
 return jsonb_build_object('material_needs',coalesce((select jsonb_agg(x order by x->>'material_need_id') from (select jsonb_build_object('material_need_id',n.id,'object_id',n.obyekt_id,'material_id',n.material_id,'quantity',n.quantity,'unit',n.unit) x from public.t2_material_need_v2 n where n.kompaniya_id=p_kompaniya_id and (p_loyiha_id is null or n.loyiha_id=p_loyiha_id) order by n.created_at desc limit 200) mn),'[]'::jsonb),'requests',coalesce((select jsonb_agg(x order by x->>'request_id') from (select jsonb_build_object('request_id',r.id,'material_need_id',r.material_need_id,'object_id',r.obyekt_id,'material_id',r.material_id,'quantity',r.requested_qty,'delivered_qty',r.delivered_qty,'stage',case when exists(select 1 from public.t2_procurement_receipt_v2 z where z.request_id=r.id) then 'GRN' when exists(select 1 from public.t2_procurement_award_v2 a where a.request_id=r.id) then 'AWARD' when exists(select 1 from public.t2_procurement_rfq_v2 q where q.request_id=r.id) then 'RFQ' else 'PR' end,'rfq_id',(select q.id from public.t2_procurement_rfq_v2 q where q.request_id=r.id order by q.id desc limit 1),'award_id',(select a.id from public.t2_procurement_award_v2 a where a.request_id=r.id order by a.id desc limit 1),'remaining_qty',r.requested_qty-r.delivered_qty) x from public.t2_erp_taminot r join public.t2_obyekt o on o.id=r.obyekt_id where r.kompaniya_id=p_kompaniya_id and (p_loyiha_id is null or o.loyiha_id=p_loyiha_id) order by r.created_at desc limit 200) s),'[]'::jsonb)); end $$;

-- ── SCHEDULE V2 ──────────────────────────────────────────────────────────
alter table public.t2_grafik_qator add column if not exists loyiha_id bigint null references public.t2_loyiha(id), add column if not exists wbs_qator_id bigint null references public.t2_qator(id), add column if not exists baseline_boshlanish_sana date null, add column if not exists baseline_tugash_sana date null, add column if not exists actual_boshlanish_sana date null, add column if not exists actual_tugash_sana date null, add column if not exists forecast_tugash_sana date null;
create table if not exists public.t2_grafik_boglanish_v2 (id bigint generated by default as identity primary key, kompaniya_id bigint not null references public.t2_kompaniya(id), predecessor_id bigint not null references public.t2_grafik_qator(id) on delete restrict, successor_id bigint not null references public.t2_grafik_qator(id) on delete restrict, tur text not null default 'FS' check(tur in('FS','SS','FF','SF')), lag_kun integer not null default 0, operation_id uuid not null, created_by bigint not null references public.t2_foydalanuvchi(id), created_at timestamptz not null default now(), unique(kompaniya_id,operation_id), unique(predecessor_id,successor_id));
create table if not exists public.t2_grafik_progress_tarix_v2 (id bigint generated by default as identity primary key, kompaniya_id bigint not null references public.t2_kompaniya(id), grafik_id bigint not null references public.t2_grafik_qator(id), foiz numeric not null check(foiz between 0 and 100), holat text not null, actual_boshlanish_sana date null, actual_tugash_sana date null, forecast_tugash_sana date null, base_version integer not null, operation_id uuid not null, actor_id bigint not null references public.t2_foydalanuvchi(id), created_at timestamptz not null default now(), unique(kompaniya_id,operation_id));
create index if not exists t2_grafik_v3_project_idx on public.t2_grafik_qator(kompaniya_id,loyiha_id,tugash_sana);

create or replace function public.t2_schedule_dependency_create_v2(p_kompaniya_id bigint,p_actor_id bigint,p_predecessor_id bigint,p_successor_id bigint,p_tur text,p_lag_kun integer,p_operation_id uuid)
returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$ declare v_id bigint; v_p record; v_s record; begin
 perform public.t2_v3_require_write(p_kompaniya_id,p_actor_id); if p_operation_id is null or p_predecessor_id=p_successor_id then raise exception 'DEPENDENCY_FIELDS_INVALID'; end if;
 select id into v_id from public.t2_grafik_boglanish_v2 where kompaniya_id=p_kompaniya_id and operation_id=p_operation_id; if found then return jsonb_build_object('ok',true,'dependency_id',v_id,'idempotent',true); end if;
 select g.id,g.obyekt_id,g.loyiha_id into v_p from public.t2_grafik_qator g where g.id=p_predecessor_id and g.kompaniya_id=p_kompaniya_id; select g.id,g.obyekt_id,g.loyiha_id into v_s from public.t2_grafik_qator g where g.id=p_successor_id and g.kompaniya_id=p_kompaniya_id; if not found or v_p.obyekt_id<>v_s.obyekt_id or v_p.loyiha_id is distinct from v_s.loyiha_id then raise exception 'CROSS_PROJECT_DEPENDENCY_FORBIDDEN' using errcode='42501'; end if;
 if p_tur not in('FS','SS','FF','SF') then raise exception 'DEPENDENCY_TYPE_INVALID'; end if;
 if exists(with recursive walk(id) as (select p_successor_id union select d.successor_id from public.t2_grafik_boglanish_v2 d join walk w on d.predecessor_id=w.id where d.kompaniya_id=p_kompaniya_id) select 1 from walk where id=p_predecessor_id) then raise exception 'SCHEDULE_CYCLE' using errcode='23514'; end if;
 insert into public.t2_grafik_boglanish_v2(kompaniya_id,predecessor_id,successor_id,tur,lag_kun,operation_id,created_by) values(p_kompaniya_id,p_predecessor_id,p_successor_id,p_tur,coalesce(p_lag_kun,0),p_operation_id,p_actor_id) returning id into v_id; return jsonb_build_object('ok',true,'dependency_id',v_id,'idempotent',false); end $$;

create or replace function public.t2_schedule_progress_record_v2(p_kompaniya_id bigint,p_actor_id bigint,p_grafik_id bigint,p_expected_version integer,p_foiz numeric,p_holat text,p_actual_start date,p_actual_finish date,p_forecast_finish date,p_operation_id uuid)
returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$ declare v public.t2_grafik_qator%rowtype; begin
 perform public.t2_v3_require_write(p_kompaniya_id,p_actor_id); if p_operation_id is null or p_foiz not between 0 and 100 then raise exception 'SCHEDULE_PROGRESS_INVALID'; end if;
 if exists(select 1 from public.t2_grafik_progress_tarix_v2 where kompaniya_id=p_kompaniya_id and operation_id=p_operation_id) then return jsonb_build_object('ok',true,'idempotent',true); end if;
 select * into v from public.t2_grafik_qator where id=p_grafik_id and kompaniya_id=p_kompaniya_id for update; if not found then raise exception 'SCHEDULE_ACTIVITY_NOT_FOUND' using errcode='42501'; end if; if v.versiya<>p_expected_version then raise exception 'STALE_VERSION' using errcode='40001'; end if;
 update public.t2_grafik_qator set foiz=p_foiz,holat=p_holat,actual_boshlanish_sana=coalesce(p_actual_start,actual_boshlanish_sana),actual_tugash_sana=coalesce(p_actual_finish,actual_tugash_sana),forecast_tugash_sana=coalesce(p_forecast_finish,forecast_tugash_sana),versiya=versiya+1 where id=v.id returning * into v;
 insert into public.t2_grafik_progress_tarix_v2(kompaniya_id,grafik_id,foiz,holat,actual_boshlanish_sana,actual_tugash_sana,forecast_tugash_sana,base_version,operation_id,actor_id) values(p_kompaniya_id,v.id,p_foiz,p_holat,p_actual_start,p_actual_finish,p_forecast_finish,p_expected_version,p_operation_id,p_actor_id);
 return jsonb_build_object('ok',true,'activity_id',v.id,'version',v.versiya,'idempotent',false); end $$;

create or replace function public.t2_schedule_baseline_lock_v2(p_kompaniya_id bigint,p_actor_id bigint,p_loyiha_id bigint,p_operation_id uuid)
returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$ declare v_rol text; v_count integer; begin
  v_rol:=public.t2_v3_require_member(p_kompaniya_id,p_actor_id); if v_rol not in('superadmin','admin','pto') then raise exception 'BASELINE_PERMISSION_DENIED' using errcode='42501'; end if;
  if p_operation_id is null then raise exception 'OPERATION_ID_REQUIRED'; end if;
  if not exists(select 1 from public.t2_loyiha where id=p_loyiha_id and kompaniya_id=p_kompaniya_id) then raise exception 'PROJECT_COMPANY_MISMATCH' using errcode='42501'; end if;
  update public.t2_grafik_qator set baseline_boshlanish_sana=boshlanish_sana,baseline_tugash_sana=tugash_sana where kompaniya_id=p_kompaniya_id and loyiha_id=p_loyiha_id and baseline_boshlanish_sana is null and baseline_tugash_sana is null;
  get diagnostics v_count=row_count; return jsonb_build_object('ok',true,'locked_count',v_count,'operation_id',p_operation_id); end $$;

create or replace function public.t2_schedule_overview_v2(p_kompaniya_id bigint,p_actor_id bigint,p_loyiha_id bigint)
returns jsonb language plpgsql stable security definer set search_path=public,pg_temp as $$ begin
 perform public.t2_v3_require_member(p_kompaniya_id,p_actor_id); if not exists(select 1 from public.t2_loyiha where id=p_loyiha_id and kompaniya_id=p_kompaniya_id) then raise exception 'PROJECT_COMPANY_MISMATCH' using errcode='42501'; end if;
 return jsonb_build_object('activities',coalesce((select jsonb_agg(x order by x->>'forecast_finish') from (select jsonb_build_object('activity_id',g.id,'object_id',g.obyekt_id,'wbs_qator_id',g.wbs_qator_id,'nom',g.nom,'progress',g.foiz,'holat',g.holat,'baseline_start',g.baseline_boshlanish_sana,'baseline_finish',g.baseline_tugash_sana,'forecast_finish',coalesce(g.forecast_tugash_sana,g.tugash_sana),'variance_days',case when g.baseline_tugash_sana is null or coalesce(g.forecast_tugash_sana,g.tugash_sana) is null then null else coalesce(g.forecast_tugash_sana,g.tugash_sana)-g.baseline_tugash_sana end,'late',coalesce(g.forecast_tugash_sana,g.tugash_sana)<current_date and g.foiz<100,'dependencies',coalesce((select jsonb_agg(d.predecessor_id) from public.t2_grafik_boglanish_v2 d where d.successor_id=g.id),'[]'::jsonb),'procurement_risk',exists(select 1 from public.t2_erp_taminot r where r.obyekt_id=g.obyekt_id and r.kompaniya_id=p_kompaniya_id and r.status in('draft','submitted','approved','procurement','ordered','partially_delivered') and r.required_date is not null and coalesce(g.forecast_tugash_sana,g.tugash_sana) is not null and r.required_date>coalesce(g.forecast_tugash_sana,g.tugash_sana))) x from public.t2_grafik_qator g where g.kompaniya_id=p_kompaniya_id and g.loyiha_id=p_loyiha_id order by coalesce(g.forecast_tugash_sana,g.tugash_sana) nulls last limit 500) s),'[]'::jsonb)); end $$;

alter table public.t2_commercial_operation enable row level security; alter table public.t2_change_order enable row level security; alter table public.t2_change_order_decision_operation enable row level security; alter table public.t2_material_need_v2 enable row level security; alter table public.t2_procurement_rfq_v2 enable row level security; alter table public.t2_procurement_bid_v2 enable row level security; alter table public.t2_procurement_award_v2 enable row level security; alter table public.t2_procurement_receipt_v2 enable row level security; alter table public.t2_procurement_warehouse_movement_v2 enable row level security; alter table public.t2_grafik_boglanish_v2 enable row level security; alter table public.t2_grafik_progress_tarix_v2 enable row level security;
revoke all on function public.t2_v3_require_member(bigint,bigint),public.t2_v3_require_write(bigint,bigint),public.t2_v3_require_approve(bigint,bigint),public.t2_commercial_contract_get_v2(bigint,bigint,bigint),public.t2_commercial_contract_update_v2(bigint,bigint,bigint,integer,uuid,jsonb),public.t2_change_order_create_v2(bigint,bigint,bigint,uuid,text,text,numeric,bigint,bigint),public.t2_change_order_decide_v2(bigint,bigint,bigint,integer,uuid,text,text),public.t2_material_need_create_v2(bigint,bigint,bigint,bigint,bigint,numeric,text,date,uuid),public.t2_procurement_pr_create_v2(bigint,bigint,bigint,text,uuid),public.t2_procurement_rfq_create_v2(bigint,bigint,bigint,uuid),public.t2_procurement_bid_submit_v2(bigint,bigint,bigint,bigint,numeric,uuid),public.t2_procurement_award_v2(bigint,bigint,bigint,bigint,text,uuid),public.t2_procurement_receipt_record_v2(bigint,bigint,bigint,bigint,numeric,uuid),public.t2_procurement_overview_v2(bigint,bigint,bigint),public.t2_schedule_dependency_create_v2(bigint,bigint,bigint,bigint,text,integer,uuid),public.t2_schedule_progress_record_v2(bigint,bigint,bigint,integer,numeric,text,date,date,date,uuid),public.t2_schedule_baseline_lock_v2(bigint,bigint,bigint,uuid),public.t2_schedule_overview_v2(bigint,bigint,bigint) from public,anon,authenticated;
grant execute on function public.t2_commercial_contract_get_v2(bigint,bigint,bigint),public.t2_commercial_contract_update_v2(bigint,bigint,bigint,integer,uuid,jsonb),public.t2_change_order_create_v2(bigint,bigint,bigint,uuid,text,text,numeric,bigint,bigint),public.t2_change_order_decide_v2(bigint,bigint,bigint,integer,uuid,text,text),public.t2_material_need_create_v2(bigint,bigint,bigint,bigint,bigint,numeric,text,date,uuid),public.t2_procurement_pr_create_v2(bigint,bigint,bigint,text,uuid),public.t2_procurement_rfq_create_v2(bigint,bigint,bigint,uuid),public.t2_procurement_bid_submit_v2(bigint,bigint,bigint,bigint,numeric,uuid),public.t2_procurement_award_v2(bigint,bigint,bigint,bigint,text,uuid),public.t2_procurement_receipt_record_v2(bigint,bigint,bigint,bigint,numeric,uuid),public.t2_procurement_overview_v2(bigint,bigint,bigint),public.t2_schedule_dependency_create_v2(bigint,bigint,bigint,bigint,text,integer,uuid),public.t2_schedule_progress_record_v2(bigint,bigint,bigint,integer,numeric,text,date,date,date,uuid),public.t2_schedule_baseline_lock_v2(bigint,bigint,bigint,uuid),public.t2_schedule_overview_v2(bigint,bigint,bigint) to service_role;
commit;
