begin;
drop function if exists public.t2_schedule_overview_v2(bigint,bigint,bigint);
drop function if exists public.t2_schedule_baseline_lock_v2(bigint,bigint,bigint,uuid);
drop function if exists public.t2_schedule_progress_record_v2(bigint,bigint,bigint,integer,numeric,text,date,date,date,uuid);
drop function if exists public.t2_schedule_dependency_create_v2(bigint,bigint,bigint,bigint,text,integer,uuid);
drop function if exists public.t2_procurement_overview_v2(bigint,bigint,bigint);
drop function if exists public.t2_procurement_receipt_record_v2(bigint,bigint,bigint,bigint,numeric,uuid);
drop function if exists public.t2_procurement_award_v2(bigint,bigint,bigint,bigint,text,uuid);
drop function if exists public.t2_procurement_bid_submit_v2(bigint,bigint,bigint,bigint,numeric,uuid);
drop function if exists public.t2_procurement_rfq_create_v2(bigint,bigint,bigint,uuid);
drop function if exists public.t2_change_order_decide_v2(bigint,bigint,bigint,integer,uuid,text,text);
drop function if exists public.t2_change_order_create_v2(bigint,bigint,bigint,uuid,text,text,numeric,bigint,bigint);
drop function if exists public.t2_commercial_contract_update_v2(bigint,bigint,bigint,integer,uuid,jsonb);
drop function if exists public.t2_commercial_contract_get_v2(bigint,bigint,bigint);
drop function if exists public.t2_procurement_pr_create_v2(bigint,bigint,bigint,text,uuid); drop function if exists public.t2_material_need_create_v2(bigint,bigint,bigint,bigint,bigint,numeric,text,date,uuid);
alter table public.t2_erp_taminot drop column if exists material_need_id;
drop table if exists public.t2_grafik_progress_tarix_v2,public.t2_grafik_boglanish_v2,public.t2_procurement_warehouse_movement_v2,public.t2_procurement_receipt_v2,public.t2_procurement_award_v2,public.t2_procurement_bid_v2,public.t2_procurement_rfq_v2,public.t2_material_need_v2,public.t2_change_order_decision_operation,public.t2_change_order,public.t2_commercial_operation;
alter table public.t2_grafik_qator drop column if exists loyiha_id,drop column if exists wbs_qator_id,drop column if exists baseline_boshlanish_sana,drop column if exists baseline_tugash_sana,drop column if exists actual_boshlanish_sana,drop column if exists actual_tugash_sana,drop column if exists forecast_tugash_sana;
alter table public.t2_shartnoma drop constraint if exists t2_shartnoma_v3_terms,drop column if exists valuta,drop column if exists avans_summa,drop column if exists ushlab_qolish_foiz,drop column if exists tolov_muddati_kun,drop column if exists kafolat_muddati_kun;
drop function if exists public.t2_v3_require_approve(bigint,bigint); drop function if exists public.t2_v3_require_write(bigint,bigint); drop function if exists public.t2_v3_require_member(bigint,bigint);
commit;
