-- SUPERSEDED 2026-09-01: folded into 20260830052000_t2_company_storage_foundation_v1.sql
-- (corrected consolidation). Legacy-write policy (LEGACY_WORKSPACE_FORBIDDEN in
-- t2_project_storage_provision_v1 / t2_object_create_v1) now lives there.
-- Applied to production as the single migration t2_company_storage_foundation_v1.
