-- T2 F2 import recovery / soft-cancel (source-only until DB owner applies it)
--
-- A worker timeout is not a completion signal. Recovery preserves cursor,
-- durable draft rows and completed_at=NULL; it only moves an interrupted job
-- to a safe paused state for an explicit resume/review.

begin;

alter table public.t2_f2_import_job
  add column if not exists lease_token uuid,
  add column if not exists lease_expires_at timestamptz,
  add column if not exists last_heartbeat_at timestamptz,
  add column if not exists recovery_count integer not null default 0,
  add column if not exists recovery_required boolean not null default false;

do $$
begin
  if exists (select 1 from pg_constraint where conname = 't2_f2_import_job_status_check') then
    alter table public.t2_f2_import_job drop constraint t2_f2_import_job_status_check;
  end if;
  alter table public.t2_f2_import_job add constraint t2_f2_import_job_status_check
    check (status in ('queued','running','paused','review','completed','failed','cancelled'));
end $$;

create table if not exists public.t2_f2_import_job_recovery (
  id bigint generated by default as identity primary key,
  kompaniya_id bigint not null references public.t2_kompaniya(id),
  job_id bigint not null references public.t2_f2_import_job(id) on delete restrict,
  from_status text not null,
  to_status text not null default 'paused',
  operation_id uuid not null unique,
  actor_id bigint not null references public.t2_foydalanuvchi(id),
  reason text not null,
  cursor_snapshot jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint t2_f2_job_recovery_from_check check (from_status in ('running','review')),
  constraint t2_f2_job_recovery_to_check check (to_status = 'paused')
);
create index if not exists t2_f2_job_recovery_job_idx
  on public.t2_f2_import_job_recovery (job_id, created_at desc);
alter table public.t2_f2_import_job_recovery enable row level security;
revoke all on table public.t2_f2_import_job_recovery from public, anon, authenticated;

create table if not exists public.t2_f2_import_job_cancel_event (
  id bigint generated by default as identity primary key,
  kompaniya_id bigint not null references public.t2_kompaniya(id),
  job_id bigint not null references public.t2_f2_import_job(id) on delete restrict,
  from_status text not null,
  to_status text not null,
  operation_id uuid not null unique,
  actor_id bigint not null references public.t2_foydalanuvchi(id),
  reason text not null,
  created_at timestamptz not null default now()
);
create index if not exists t2_f2_job_cancel_event_job_idx
  on public.t2_f2_import_job_cancel_event (job_id, created_at desc);
alter table public.t2_f2_import_job_cancel_event enable row level security;
revoke all on table public.t2_f2_import_job_cancel_event from public, anon, authenticated;

create or replace function public.t2_f2_import_job_recover_v1(
  p_job_id bigint,
  p_actor_id bigint,
  p_expected_versiya integer,
  p_operation_id uuid,
  p_stale_after_seconds integer default 900
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_job public.t2_f2_import_job;
  v_recovery public.t2_f2_import_job_recovery;
  v_stale boolean;
  v_new_version integer;
  v_reason text;
begin
  if p_operation_id is null then return jsonb_build_object('ok', false, 'code', 'OPERATION_ID_REQUIRED'); end if;
  if p_expected_versiya is null then return jsonb_build_object('ok', false, 'code', 'EXPECTED_VERSION_REQUIRED'); end if;
  if p_stale_after_seconds is null or p_stale_after_seconds not between 60 and 86400 then
    return jsonb_build_object('ok', false, 'code', 'STALE_WINDOW_OUT_OF_RANGE');
  end if;
  perform pg_advisory_xact_lock(hashtextextended(p_operation_id::text, 0));

  select * into v_recovery from public.t2_f2_import_job_recovery where operation_id = p_operation_id;
  if found then
    perform public.t2_actor_kompaniya_azo_tekshir(v_recovery.kompaniya_id, p_actor_id);
    if v_recovery.job_id <> p_job_id then
      return jsonb_build_object('ok', false, 'code', 'OPERATION_REPLAY_CONFLICT');
    end if;
    return jsonb_build_object('ok', true, 'retry', true, 'job_id', v_recovery.job_id,
      'status', v_recovery.to_status, 'recovery_id', v_recovery.id);
  end if;

  select * into v_job from public.t2_f2_import_job where id = p_job_id for update;
  if not found then return jsonb_build_object('ok', false, 'code', 'JOB_NOT_FOUND'); end if;
  perform public.t2_actor_kompaniya_azo_tekshir(v_job.kompaniya_id, p_actor_id);

  if v_job.versiya <> p_expected_versiya then
    return jsonb_build_object('ok', false, 'code', 'STALE_VERSION', 'versiya', v_job.versiya);
  end if;
  if v_job.status in ('completed','failed','cancelled') then
    return jsonb_build_object('ok', false, 'code', 'TERMINAL_JOB', 'status', v_job.status);
  end if;
  if v_job.status not in ('running','review') then
    return jsonb_build_object('ok', false, 'code', 'JOB_NOT_RECOVERABLE', 'status', v_job.status);
  end if;

  -- `review` is explicitly held for human review; it is recoverable even if
  -- recently updated. `running` requires a stale timestamp or expired lease.
  v_stale := v_job.status = 'review'
    or v_job.updated_at < now() - make_interval(secs => p_stale_after_seconds)
    or (v_job.lease_expires_at is not null and v_job.lease_expires_at <= now());
  if not v_stale then
    return jsonb_build_object('ok', false, 'code', 'JOB_NOT_STALE', 'status', v_job.status,
      'updated_at', v_job.updated_at, 'lease_expires_at', v_job.lease_expires_at);
  end if;

  v_reason := case when v_job.status = 'review'
    then 'review_job_recovery_required'
    else 'worker_lease_expired_recovery_required' end;
  update public.t2_f2_import_job
  set status = 'paused',
      last_error = v_reason,
      recovery_required = true,
      recovery_count = recovery_count + 1,
      lease_token = null,
      lease_expires_at = null,
      last_heartbeat_at = now(),
      versiya = versiya + 1,
      updated_at = now()
  where id = p_job_id and versiya = p_expected_versiya
  returning versiya into v_new_version;
  if not found then return jsonb_build_object('ok', false, 'code', 'STALE_VERSION'); end if;

  insert into public.t2_f2_import_job_recovery
    (kompaniya_id, job_id, from_status, to_status, operation_id, actor_id, reason, cursor_snapshot)
  values
    (v_job.kompaniya_id, p_job_id, v_job.status, 'paused', p_operation_id, p_actor_id, v_reason, v_job.cursor)
  returning * into v_recovery;

  perform public.t2_audit_yoz(v_job.kompaniya_id, 'f2_import_job_recovered', 'f2', v_job.obyekt_id,
    format('job_id=%s; from=%s; to=paused; versiya=%s; operation_id=%s', p_job_id, v_job.status, v_new_version, p_operation_id),
    'actor:' || p_actor_id, null);
  return jsonb_build_object('ok', true, 'job_id', p_job_id, 'from_status', v_job.status,
    'status', 'paused', 'recovery_required', true, 'versiya', v_new_version,
    'recovery_id', v_recovery.id, 'completed_at', null);
end $$;

create or replace function public.t2_f2_import_job_cancel_v1(
  p_job_id bigint,
  p_actor_id bigint,
  p_expected_versiya integer,
  p_operation_id uuid,
  p_reason text
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_job public.t2_f2_import_job;
  v_event public.t2_f2_import_job_cancel_event;
  v_reason text := nullif(btrim(p_reason), '');
  v_new_version integer;
begin
  if p_operation_id is null then return jsonb_build_object('ok', false, 'code', 'OPERATION_ID_REQUIRED'); end if;
  if p_expected_versiya is null then return jsonb_build_object('ok', false, 'code', 'EXPECTED_VERSION_REQUIRED'); end if;
  if v_reason is null then return jsonb_build_object('ok', false, 'code', 'REASON_REQUIRED'); end if;
  if length(v_reason) > 2000 then return jsonb_build_object('ok', false, 'code', 'REASON_TOO_LONG'); end if;
  perform pg_advisory_xact_lock(hashtextextended(p_operation_id::text, 0));
  select * into v_event from public.t2_f2_import_job_cancel_event where operation_id = p_operation_id;
  if found then
    perform public.t2_actor_kompaniya_azo_tekshir(v_event.kompaniya_id, p_actor_id);
    if v_event.job_id <> p_job_id then
      return jsonb_build_object('ok', false, 'code', 'OPERATION_REPLAY_CONFLICT');
    end if;
    return jsonb_build_object('ok', true, 'retry', v_event.to_status = 'cancelled', 'job_id', v_event.job_id, 'status', v_event.to_status);
  end if;
  select * into v_job from public.t2_f2_import_job where id = p_job_id for update;
  if not found then return jsonb_build_object('ok', false, 'code', 'JOB_NOT_FOUND'); end if;
  perform public.t2_actor_kompaniya_azo_tekshir(v_job.kompaniya_id, p_actor_id);
  if v_job.versiya <> p_expected_versiya then return jsonb_build_object('ok', false, 'code', 'STALE_VERSION', 'versiya', v_job.versiya); end if;
  if v_job.status in ('completed','failed','cancelled') then
    insert into public.t2_f2_import_job_cancel_event
      (kompaniya_id, job_id, from_status, to_status, operation_id, actor_id, reason)
    values (v_job.kompaniya_id, p_job_id, v_job.status, v_job.status, p_operation_id, p_actor_id, v_reason);
    return jsonb_build_object('ok', v_job.status = 'cancelled', 'retry', v_job.status = 'cancelled', 'job_id', p_job_id, 'status', v_job.status, 'versiya', v_job.versiya);
  end if;

  update public.t2_f2_import_job
  set status = 'cancelled', last_error = v_reason, recovery_required = false,
      lease_token = null, lease_expires_at = null, completed_at = now(),
      versiya = versiya + 1, updated_at = now()
  where id = p_job_id and versiya = p_expected_versiya
  returning versiya into v_new_version;
  if not found then return jsonb_build_object('ok', false, 'code', 'STALE_VERSION'); end if;
  insert into public.t2_f2_import_job_cancel_event
    (kompaniya_id, job_id, from_status, to_status, operation_id, actor_id, reason)
  values (v_job.kompaniya_id, p_job_id, v_job.status, 'cancelled', p_operation_id, p_actor_id, v_reason);
  perform public.t2_audit_yoz(v_job.kompaniya_id, 'f2_import_job_cancelled', 'f2', v_job.obyekt_id,
    format('job_id=%s; reason=%s; operation_id=%s', p_job_id, v_reason, p_operation_id),
    'actor:' || p_actor_id, null);
  return jsonb_build_object('ok', true, 'job_id', p_job_id, 'status', 'cancelled', 'versiya', v_new_version, 'completed_at', now());
end $$;

revoke all on function public.t2_f2_import_job_recover_v1(bigint,bigint,integer,uuid,integer) from public, anon, authenticated;
revoke all on function public.t2_f2_import_job_cancel_v1(bigint,bigint,integer,uuid,text) from public, anon, authenticated;
grant execute on function public.t2_f2_import_job_recover_v1(bigint,bigint,integer,uuid,integer) to service_role;
grant execute on function public.t2_f2_import_job_cancel_v1(bigint,bigint,integer,uuid,text) to service_role;

comment on table public.t2_f2_import_job_recovery is
  'Append-only F2 recovery events. Recovery pauses stale/review jobs and preserves cursor/drafts; it never fabricates completion.';
comment on table public.t2_f2_import_job_cancel_event is
  'Append-only F2 soft-cancel events. A cancelled job and its draft rows are retained for audit/review.';

commit;
