-- T2 F2 lifecycle / approval history (source-only until explicitly applied)
--
-- Compatibility rule: existing `t2_akt.holat` values remain the legacy
-- projection (`qoralama`, `tasdiqlangan`, `bekor`). The additive
-- `lifecycle_status` column is the canonical workflow state so existing
-- readers are not silently broken while new transitions become explicit.
-- `approved` rows are immutable. A correction creates a new draft row and a
-- link; it never mutates or deletes the approved source row.

begin;

alter table public.t2_akt
  add column if not exists lifecycle_status text,
  add column if not exists lifecycle_updated_at timestamptz,
  add column if not exists lifecycle_updated_by bigint,
  add column if not exists lifecycle_reason text,
  add column if not exists lifecycle_submitted_at timestamptz,
  add column if not exists lifecycle_checked_at timestamptz,
  add column if not exists lifecycle_approved_at timestamptz,
  add column if not exists lifecycle_rejected_at timestamptz,
  add column if not exists lifecycle_cancelled_at timestamptz,
  add column if not exists lifecycle_superseded_at timestamptz,
  add column if not exists correction_of_akt_id bigint;

-- Existing rows are mapped conservatively. No amount, quantity, date, or
-- approval value is invented; only the already persisted legacy status is
-- projected into the new workflow vocabulary.
update public.t2_akt
set lifecycle_status = case holat
  when 'tasdiqlangan' then 'approved'
  when 'bekor' then 'cancelled'
  else 'draft'
end
where lifecycle_status is null;

update public.t2_akt
set lifecycle_updated_at = coalesce(lifecycle_updated_at, yangilandi, yaratildi),
    lifecycle_approved_at = case when lifecycle_status = 'approved' then coalesce(lifecycle_approved_at, yangilandi, yaratildi) else lifecycle_approved_at end,
    lifecycle_cancelled_at = case when lifecycle_status = 'cancelled' then coalesce(lifecycle_cancelled_at, yangilandi, yaratildi) else lifecycle_cancelled_at end
where lifecycle_updated_at is null
   or lifecycle_status in ('approved', 'cancelled');

alter table public.t2_akt
  alter column lifecycle_status set default 'draft',
  alter column lifecycle_status set not null;

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 't2_akt_lifecycle_status_check') then
    alter table public.t2_akt add constraint t2_akt_lifecycle_status_check
      check (lifecycle_status in ('draft','submitted','checked','approved','rejected','cancelled','superseded'));
  end if;
  if not exists (select 1 from pg_constraint where conname = 't2_akt_lifecycle_actor_fkey') then
    alter table public.t2_akt add constraint t2_akt_lifecycle_actor_fkey
      foreign key (lifecycle_updated_by) references public.t2_foydalanuvchi(id);
  end if;
  if not exists (select 1 from pg_constraint where conname = 't2_akt_correction_of_fkey') then
    alter table public.t2_akt add constraint t2_akt_correction_of_fkey
      foreign key (correction_of_akt_id) references public.t2_akt(id) on delete restrict;
  end if;
end $$;

create table if not exists public.t2_akt_holat_tarix (
  id bigint generated by default as identity primary key,
  kompaniya_id bigint not null references public.t2_kompaniya(id),
  akt_id bigint not null references public.t2_akt(id) on delete restrict,
  from_status text,
  to_status text not null,
  reason text,
  actor_id bigint references public.t2_foydalanuvchi(id),
  operation_id uuid,
  created_at timestamptz not null default now(),
  constraint t2_akt_holat_tarix_from_check check (from_status is null or from_status in ('draft','submitted','checked','approved','rejected','cancelled','superseded')),
  constraint t2_akt_holat_tarix_to_check check (to_status in ('draft','submitted','checked','approved','rejected','cancelled','superseded'))
);

create table if not exists public.t2_akt_correction_link (
  id bigint generated by default as identity primary key,
  kompaniya_id bigint not null references public.t2_kompaniya(id),
  original_akt_id bigint not null references public.t2_akt(id) on delete restrict,
  replacement_akt_id bigint not null references public.t2_akt(id) on delete restrict,
  relation text not null default 'supersedes',
  reason text,
  actor_id bigint references public.t2_foydalanuvchi(id),
  operation_id uuid not null,
  created_at timestamptz not null default now(),
  constraint t2_akt_correction_relation_check check (relation = 'supersedes'),
  constraint t2_akt_correction_pair_check check (original_akt_id <> replacement_akt_id),
  constraint t2_akt_correction_pair_unique unique (original_akt_id, replacement_akt_id),
  constraint t2_akt_correction_operation_unique unique (operation_id)
);

create index if not exists t2_akt_holat_tarix_akt_created_idx
  on public.t2_akt_holat_tarix (akt_id, created_at, id);
create unique index if not exists t2_akt_holat_tarix_operation_unique
  on public.t2_akt_holat_tarix (akt_id, operation_id)
  where operation_id is not null;
create index if not exists t2_akt_holat_tarix_company_idx
  on public.t2_akt_holat_tarix (kompaniya_id, created_at desc);
create index if not exists t2_akt_correction_original_idx
  on public.t2_akt_correction_link (original_akt_id, created_at desc);
create index if not exists t2_akt_correction_replacement_idx
  on public.t2_akt_correction_link (replacement_akt_id);

alter table public.t2_akt_holat_tarix enable row level security;
alter table public.t2_akt_correction_link enable row level security;
revoke all on table public.t2_akt_holat_tarix, public.t2_akt_correction_link from public, anon, authenticated;

create or replace function public.t2_akt_lifecycle_projection_guard_v1()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_internal text := current_setting('t2.akt.lifecycle_transition', true);
begin
  if tg_op = 'INSERT' then
    if new.lifecycle_status is null or (new.lifecycle_status = 'draft' and new.holat in ('tasdiqlangan','bekor')) then
      new.lifecycle_status := case new.holat
        when 'tasdiqlangan' then 'approved'
        when 'bekor' then 'cancelled'
        else 'draft'
      end;
    end if;
    if new.lifecycle_status = 'approved' then new.holat := 'tasdiqlangan';
    elsif new.lifecycle_status in ('cancelled','superseded') then new.holat := 'bekor';
    else new.holat := 'qoralama';
    end if;
    new.lifecycle_updated_at := coalesce(new.lifecycle_updated_at, now());
    return new;
  end if;

  -- A previously approved header cannot be changed in place. `yangilandi`
  -- is excluded because existing audit/update triggers may refresh that
  -- technical timestamp; all business fields remain byte-for-byte stable.
  if old.lifecycle_status = 'approved'
     and (to_jsonb(new) - 'yangilandi') is distinct from (to_jsonb(old) - 'yangilandi') then
    raise exception 'approved akt immutable; correction uchun yangi revision yarating'
      using errcode = '55000';
  end if;

  if new.lifecycle_status is distinct from old.lifecycle_status then
    if coalesce(v_internal, '') <> '1' then
      raise exception 'lifecycle_status faqat t2_akt_lifecycle_transition_v1 orqali o''zgaradi'
        using errcode = '42501';
    end if;
    if new.lifecycle_status = 'approved' then new.holat := 'tasdiqlangan';
    elsif new.lifecycle_status in ('cancelled','superseded') then new.holat := 'bekor';
    else new.holat := 'qoralama';
    end if;
  elsif new.holat is distinct from old.holat then
    -- Legacy RPC compatibility. Old confirm/cancel functions still update
    -- `holat`; project that change into lifecycle history rather than
    -- silently losing the workflow state.
    if new.holat = 'tasdiqlangan' then new.lifecycle_status := 'approved';
    elsif new.holat = 'bekor' then new.lifecycle_status := 'cancelled';
    elsif new.holat = 'qoralama' then new.lifecycle_status := 'draft';
    else
      raise exception 'noma''lum legacy akt holati' using errcode = '22023';
    end if;
    new.lifecycle_updated_at := now();
  end if;
  return new;
end $$;

create or replace function public.t2_akt_lifecycle_history_capture_v1()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_actor_id bigint;
  v_operation_id uuid;
  v_reason text;
begin
  if new.lifecycle_status is not distinct from old.lifecycle_status then return new; end if;
  v_actor_id := nullif(current_setting('t2.akt.actor_id', true), '')::bigint;
  v_operation_id := nullif(current_setting('t2.akt.operation_id', true), '')::uuid;
  v_reason := coalesce(new.lifecycle_reason, nullif(current_setting('t2.akt.reason', true), ''));
  -- Old rows with no tenant cannot be safely attributed to a history tenant;
  -- the new RPC rejects them, while unrelated legacy updates must not fail.
  if new.kompaniya_id is null then return new; end if;
  if v_operation_id is null or not exists (
    select 1 from public.t2_akt_holat_tarix h
    where h.akt_id = new.id and h.operation_id = v_operation_id
      and h.to_status = new.lifecycle_status
  ) then
    insert into public.t2_akt_holat_tarix
      (kompaniya_id, akt_id, from_status, to_status, reason, actor_id, operation_id)
    values
      (new.kompaniya_id, new.id, old.lifecycle_status, new.lifecycle_status,
       v_reason, v_actor_id, v_operation_id);
  end if;
  return new;
end $$;

drop trigger if exists t2_akt_lifecycle_projection_guard on public.t2_akt;
create trigger t2_akt_lifecycle_projection_guard
before insert or update on public.t2_akt
for each row execute function public.t2_akt_lifecycle_projection_guard_v1();

drop trigger if exists t2_akt_lifecycle_history_capture on public.t2_akt;
create trigger t2_akt_lifecycle_history_capture
after update on public.t2_akt
for each row execute function public.t2_akt_lifecycle_history_capture_v1();

create or replace function public.t2_akt_lifecycle_transition_v1(
  p_kompaniya_id bigint,
  p_akt_id bigint,
  p_to_status text,
  p_actor_id bigint,
  p_expected_version integer,
  p_operation_id uuid,
  p_reason text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_akt public.t2_akt;
  v_history public.t2_akt_holat_tarix;
  v_new_version integer;
  v_reason text := nullif(btrim(p_reason), '');
  v_allowed boolean := false;
begin
  if p_operation_id is null then return jsonb_build_object('ok', false, 'code', 'OPERATION_ID_REQUIRED'); end if;
  if p_expected_version is null then return jsonb_build_object('ok', false, 'code', 'EXPECTED_VERSION_REQUIRED'); end if;
  if p_to_status is null or p_to_status not in ('draft','submitted','checked','approved','rejected','cancelled','superseded') then
    return jsonb_build_object('ok', false, 'code', 'INVALID_LIFECYCLE_STATUS');
  end if;
  if p_to_status in ('rejected','cancelled') and v_reason is null then
    return jsonb_build_object('ok', false, 'code', 'REASON_REQUIRED');
  end if;
  if v_reason is not null and length(v_reason) > 2000 then
    return jsonb_build_object('ok', false, 'code', 'REASON_TOO_LONG');
  end if;

  perform pg_advisory_xact_lock(hashtextextended(p_operation_id::text, 0));
  perform public.t2_actor_kompaniya_azo_tekshir(p_kompaniya_id, p_actor_id);

  if exists (
    select 1 from public.t2_akt_holat_tarix h
    where h.operation_id = p_operation_id and h.akt_id <> p_akt_id
  ) then
    return jsonb_build_object('ok', false, 'code', 'OPERATION_REPLAY_CONFLICT');
  end if;

  select * into v_akt
  from public.t2_akt
  where id = p_akt_id and kompaniya_id = p_kompaniya_id
  for update;
  if not found then return jsonb_build_object('ok', false, 'code', 'AKT_NOT_FOUND'); end if;

  select * into v_history
  from public.t2_akt_holat_tarix h
  where h.akt_id = p_akt_id and h.operation_id = p_operation_id
  order by h.id desc limit 1;
  if found then
    if v_history.to_status <> p_to_status then
      return jsonb_build_object('ok', false, 'code', 'OPERATION_REPLAY_CONFLICT');
    end if;
    return jsonb_build_object('ok', true, 'retry', true, 'akt_id', p_akt_id,
      'from_status', v_history.from_status, 'status', v_history.to_status,
      'version', v_akt.versiya, 'history_id', v_history.id);
  end if;

  if v_akt.versiya <> p_expected_version then
    return jsonb_build_object('ok', false, 'code', 'STALE_VERSION', 'version', v_akt.versiya);
  end if;

  v_allowed := (v_akt.lifecycle_status, p_to_status) in (
    ('draft','submitted'), ('draft','cancelled'),
    ('submitted','checked'), ('submitted','cancelled'),
    ('checked','approved'), ('checked','rejected'), ('checked','cancelled'),
    ('rejected','submitted'), ('rejected','cancelled'),
    ('cancelled','cancelled'), ('superseded','superseded'), ('approved','approved')
  );
  if not v_allowed then
    return jsonb_build_object('ok', false, 'code', 'INVALID_LIFECYCLE_TRANSITION',
      'from_status', v_akt.lifecycle_status, 'to_status', p_to_status);
  end if;

  -- Same-state approved retry is an audit-safe idempotent acknowledgement;
  -- no UPDATE is issued, so approved immutability is preserved.
  if v_akt.lifecycle_status = p_to_status then
    insert into public.t2_akt_holat_tarix
      (kompaniya_id, akt_id, from_status, to_status, reason, actor_id, operation_id)
    values
      (p_kompaniya_id, p_akt_id, v_akt.lifecycle_status, p_to_status,
       v_reason, p_actor_id, p_operation_id)
    returning * into v_history;
    perform public.t2_audit_yoz(p_kompaniya_id, 'akt_lifecycle_retry', 'f2', p_akt_id,
      format('from=%s; to=%s; actor_id=%s; operation_id=%s', v_akt.lifecycle_status, p_to_status, p_actor_id, p_operation_id),
      'actor:' || p_actor_id, null);
    return jsonb_build_object('ok', true, 'retry', true, 'akt_id', p_akt_id,
      'from_status', v_akt.lifecycle_status, 'status', p_to_status,
      'version', v_akt.versiya, 'history_id', v_history.id);
  end if;

  perform set_config('t2.akt.lifecycle_transition', '1', true);
  perform set_config('t2.akt.actor_id', p_actor_id::text, true);
  perform set_config('t2.akt.operation_id', p_operation_id::text, true);
  perform set_config('t2.akt.reason', coalesce(v_reason, ''), true);

  update public.t2_akt
  set lifecycle_status = p_to_status,
      lifecycle_updated_at = now(),
      lifecycle_updated_by = p_actor_id,
      lifecycle_reason = v_reason,
      lifecycle_submitted_at = case when p_to_status = 'submitted' then coalesce(lifecycle_submitted_at, now()) else lifecycle_submitted_at end,
      lifecycle_checked_at = case when p_to_status = 'checked' then coalesce(lifecycle_checked_at, now()) else lifecycle_checked_at end,
      lifecycle_approved_at = case when p_to_status = 'approved' then coalesce(lifecycle_approved_at, now()) else lifecycle_approved_at end,
      lifecycle_rejected_at = case when p_to_status = 'rejected' then coalesce(lifecycle_rejected_at, now()) else lifecycle_rejected_at end,
      lifecycle_cancelled_at = case when p_to_status = 'cancelled' then coalesce(lifecycle_cancelled_at, now()) else lifecycle_cancelled_at end,
      lifecycle_superseded_at = case when p_to_status = 'superseded' then coalesce(lifecycle_superseded_at, now()) else lifecycle_superseded_at end,
      versiya = versiya + 1,
      yangilandi = now()
  where id = p_akt_id and kompaniya_id = p_kompaniya_id and versiya = p_expected_version
  returning versiya into v_new_version;
  if not found then
    return jsonb_build_object('ok', false, 'code', 'STALE_VERSION');
  end if;

  select * into v_history
  from public.t2_akt_holat_tarix h
  where h.akt_id = p_akt_id and h.operation_id = p_operation_id
  order by h.id desc limit 1;
  perform public.t2_audit_yoz(p_kompaniya_id, 'akt_lifecycle_transition', 'f2', p_akt_id,
    format('from=%s; to=%s; actor_id=%s; operation_id=%s', v_akt.lifecycle_status, p_to_status, p_actor_id, p_operation_id),
    'actor:' || p_actor_id, null);
  return jsonb_build_object('ok', true, 'akt_id', p_akt_id,
    'from_status', v_akt.lifecycle_status, 'status', p_to_status,
    'version', v_new_version, 'history_id', v_history.id);
end $$;

create or replace function public.t2_akt_correction_create_v1(
  p_kompaniya_id bigint,
  p_actor_id bigint,
  p_source_akt_id bigint,
  p_operation_id uuid,
  p_expected_source_version integer,
  p_revision_id bigint default null,
  p_reason text default null,
  p_raqam text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_source public.t2_akt;
  v_replacement public.t2_akt;
  v_link public.t2_akt_correction_link;
  v_reason text := nullif(btrim(p_reason), '');
begin
  if p_operation_id is null then return jsonb_build_object('ok', false, 'code', 'OPERATION_ID_REQUIRED'); end if;
  if p_expected_source_version is null then return jsonb_build_object('ok', false, 'code', 'EXPECTED_VERSION_REQUIRED'); end if;
  if v_reason is not null and length(v_reason) > 2000 then return jsonb_build_object('ok', false, 'code', 'REASON_TOO_LONG'); end if;
  perform pg_advisory_xact_lock(hashtextextended(p_operation_id::text, 0));
  perform public.t2_actor_kompaniya_azo_tekshir(p_kompaniya_id, p_actor_id);

  select * into v_link from public.t2_akt_correction_link where operation_id = p_operation_id;
  if found then
    if v_link.kompaniya_id <> p_kompaniya_id or v_link.original_akt_id <> p_source_akt_id then
      return jsonb_build_object('ok', false, 'code', 'OPERATION_REPLAY_CONFLICT');
    end if;
    return jsonb_build_object('ok', true, 'retry', true, 'original_akt_id', v_link.original_akt_id,
      'replacement_akt_id', v_link.replacement_akt_id, 'status', 'draft');
  end if;

  select * into v_source
  from public.t2_akt
  where id = p_source_akt_id and kompaniya_id = p_kompaniya_id
  for update;
  if not found then return jsonb_build_object('ok', false, 'code', 'AKT_NOT_FOUND'); end if;
  if v_source.lifecycle_status <> 'approved' then
    return jsonb_build_object('ok', false, 'code', 'CORRECTION_REQUIRES_APPROVED', 'status', v_source.lifecycle_status);
  end if;
  if v_source.versiya <> p_expected_source_version then
    return jsonb_build_object('ok', false, 'code', 'STALE_VERSION', 'version', v_source.versiya);
  end if;
  if p_revision_id is not null and not exists (
    select 1 from public.t2_smeta_revision r
    where r.id = p_revision_id and r.kompaniya_id = p_kompaniya_id and r.obyekt_id = v_source.obyekt_id
  ) then
    return jsonb_build_object('ok', false, 'code', 'REVISION_TENANT_MISMATCH');
  end if;

  -- Deliberately copy the header only. Child financial rows are not copied or
  -- recalculated behind the user's back; the new draft must be imported and
  -- reviewed as a new revision.
  insert into public.t2_akt
    (obyekt_id, kompaniya_id, tur, raqam, oy, hujjat_jami, holat, fayl_id, izoh,
     versiya, operation_id, manba, kim, shartnoma_id, sana, forma3_id, davr_muhr,
     revision_id, lifecycle_status, lifecycle_updated_at, lifecycle_updated_by,
     lifecycle_reason, correction_of_akt_id)
  values
    (v_source.obyekt_id, v_source.kompaniya_id, v_source.tur,
     nullif(btrim(p_raqam), ''), v_source.oy, v_source.hujjat_jami, 'qoralama',
     v_source.fayl_id, v_reason, 1, p_operation_id, 'correction',
     'actor:' || p_actor_id, v_source.shartnoma_id, v_source.sana, v_source.forma3_id,
     v_source.davr_muhr, coalesce(p_revision_id, v_source.revision_id), 'draft', now(),
     p_actor_id, v_reason, v_source.id)
  returning * into v_replacement;

  insert into public.t2_akt_correction_link
    (kompaniya_id, original_akt_id, replacement_akt_id, reason, actor_id, operation_id)
  values
    (p_kompaniya_id, v_source.id, v_replacement.id, v_reason, p_actor_id, p_operation_id)
  returning * into v_link;

  insert into public.t2_akt_holat_tarix
    (kompaniya_id, akt_id, from_status, to_status, reason, actor_id, operation_id)
  values
    (p_kompaniya_id, v_replacement.id, null, 'draft', v_reason, p_actor_id, p_operation_id);

  perform public.t2_audit_yoz(p_kompaniya_id, 'akt_correction_created', 'f2', v_source.id,
    format('replacement_akt_id=%s; actor_id=%s; operation_id=%s', v_replacement.id, p_actor_id, p_operation_id),
    'actor:' || p_actor_id, null);
  return jsonb_build_object('ok', true, 'original_akt_id', v_source.id,
    'replacement_akt_id', v_replacement.id, 'status', v_replacement.lifecycle_status,
    'version', v_replacement.versiya, 'link_id', v_link.id);
end $$;

create or replace function public.t2_akt_lifecycle_history_v1(
  p_kompaniya_id bigint,
  p_akt_id bigint,
  p_actor_id bigint
)
returns table (
  id bigint,
  akt_id bigint,
  from_status text,
  to_status text,
  reason text,
  actor_id bigint,
  operation_id uuid,
  created_at timestamptz
)
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $$
begin
  perform public.t2_actor_kompaniya_azo_tekshir(p_kompaniya_id, p_actor_id);
  return query
  select h.id, h.akt_id, h.from_status, h.to_status, h.reason,
         h.actor_id, h.operation_id, h.created_at
  from public.t2_akt_holat_tarix h
  where h.kompaniya_id = p_kompaniya_id and h.akt_id = p_akt_id
  order by h.created_at asc, h.id asc;
end $$;

revoke all on function public.t2_akt_lifecycle_projection_guard_v1() from public, anon, authenticated;
revoke all on function public.t2_akt_lifecycle_history_capture_v1() from public, anon, authenticated;
revoke all on function public.t2_akt_lifecycle_transition_v1(bigint,bigint,text,bigint,integer,uuid,text) from public, anon, authenticated;
revoke all on function public.t2_akt_correction_create_v1(bigint,bigint,bigint,uuid,integer,bigint,text,text) from public, anon, authenticated;
revoke all on function public.t2_akt_lifecycle_history_v1(bigint,bigint,bigint) from public, anon, authenticated;
grant execute on function public.t2_akt_lifecycle_transition_v1(bigint,bigint,text,bigint,integer,uuid,text) to service_role;
grant execute on function public.t2_akt_correction_create_v1(bigint,bigint,bigint,uuid,integer,bigint,text,text) to service_role;
grant execute on function public.t2_akt_lifecycle_history_v1(bigint,bigint,bigint) to service_role;

comment on column public.t2_akt.lifecycle_status is 'Canonical F2 workflow: draft -> submitted -> checked -> approved/rejected/cancelled; approved is immutable; correction uses a new row.';
comment on table public.t2_akt_holat_tarix is 'Append-only F2 lifecycle history. Tenant-scoped and written by the lifecycle RPC/legacy compatibility trigger.';
comment on table public.t2_akt_correction_link is 'Approved F2 correction provenance. Original approved row is never mutated; replacement is a new draft.';

commit;
